pipeline:
  - module: preprocessing/scale
    meta:
      for: age
      target: 3
      path: age.scaler
  - module: preprocessing/onehot
    meta:
      for: gender
      target: [4, 5]
      values: ["M", "F"]
