input:
  format: tabular
  meta:
    - name: pclass
      type: int
      target: 0
    - name: sibsp
      type: int
      target: 1
    - name: parch
      type: int
      target: 2
    - name: age
      type: float
      preprocessed: true
    - name: gender
      type: categorical
      preprocessed: true
    - name: embarked
      type: float
      preprocessed: true
output:
  - name: prediction
    type: float
pipeline:
  - module: preprocessing/scale
    for: age
    target: 3
    meta:
      path: age.scaler
  - module: preprocessing/onehot
    for: gender
    target: [4, 5]
    meta:
      values: ["M", "F"]
  - module: preprocessing/onehot
    for: embarked
    target: [6, 7, 8]
    meta:
      values: ["C", "Q", "S"]
model:
  format: onnx
  path: titanic.onnx
interface:
  - type: rest
    port: 8080
