input:
  format: tabular
  meta:
    columns:
      - name: pclass
        type: int
        target: 0
      - name: sibsp
        type: int
        target: 1
      - name: parch
        type: int
        target: 2
      - name: age
        type: float
        preprocessed: true
      - name: gender
        type: categorical
        preprocessed: true
      - name: embarked
        type: categorical
        preprocessed: true
output:
  - name: prediction
    type: float
pipeline:
  - module: preprocessing/scale
    meta:
      for: ["age"]
      target: [3]
      path: age.scaler
  - module: preprocessing/onehot
    meta:
      for: gender
      target: [4, 5]
      values: ["M", "F"]
  - module: preprocessing/onehot
    meta:
      for: embarked
      target: [6, 7, 8]
      values: ["C", "Q", "S"]
model:
  format: onnx
  path: titanic.onnx
interface:
  - type: rest
    port: 8080
