name: lint
on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  lint:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint with chktex
      uses: j2kun/chktex-action@1.0.3

